trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  azureServiceConnection: 'pdx-eshop-rg'

stages:
# ============================
# Build Stage
# ============================
- stage: Build
  displayName: "Build Stage"
  jobs:
  - job: BuildJob
    displayName: "Build ASP.NET App"
    steps:
    - task: NuGetToolInstaller@1

    - task: NuGetCommand@2
      inputs:
        restoreSolution: '$(solution)'

    - task: VSBuild@1
      inputs:
        solution: '$(solution)'
        msbuildArgs: '/p:DeployOnBuild=true /p:WebPublishMethod=Package /p:PackageAsSingleFile=true /p:SkipInvalidConfigurations=true /p:PackageLocation="$(build.artifactStagingDirectory)"'
        platform: '$(buildPlatform)'
        configuration: '$(buildConfiguration)'

    - publish: '$(Build.ArtifactStagingDirectory)'
      artifact: drop

# ============================
# Deploy Stage
# ============================
- stage: Deploy
  displayName: "Deploy App Service"
  dependsOn:
  - Build
  variables:
    - group: EShopDev
  jobs:
  - deployment: DeployWeb
    environment: 'dev'
    strategy:
      runOnce:
        deploy:
          steps:
          - checkout: self

          - download: current
            artifact: drop

          - task: AzureWebApp@1
            displayName: 'Deploy to Azure Web App'
            inputs:
              azureSubscription: $(azureServiceConnection)
              appName: $(webAppName)
              package: '$(Pipeline.Workspace)/drop/*.zip'
